"""create Group table

Revision ID: a76e4d1efc66
Revises: 
Create Date: 2026-05-01 10:33:12.241909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76e4d1efc66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student1', sa.String(length=8), nullable=False),
    sa.Column('student2', sa.String(length=8), nullable=False),
    sa.Column('student3', sa.String(length=8), nullable=False),
    sa.Column('student4', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    # ### end Alembic commands ###
