"""add media_type column

Revision ID: 2d44a4220600
Revises: d22989e24a2d
Create Date: 2026-05-11 13:35:21.149586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d44a4220600'
down_revision = 'd22989e24a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    with op.batch_alter_table('diary_entry', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
